package com.udacity.example.jokes;

import java.util.ArrayList;
import java.util.Random;

/**
 * Created by Peretz on 2016-03-29.
 */
public class Joker {
    public String getJoke(){
        ArrayList<String> jokes=new ArrayList<>();
        jokes.add("Q: What do you call a sleeping bull? A: A bull-dozer.");
        jokes.add("Q: How do you fit more pigs on your farm? A: Build a sty-scraper.");
        jokes.add("Q: What do you get from a pampered cow? A: Spoiled milk.");
        jokes.add("Q: Why are teddy bears never hungry? A: They are always stuffed.");
        jokes.add("Q: Why do fish live in salt water? A: Because pepper makes them sneeze.");
        jokes.add("Q: Where do polar bears vote? A: The North Poll");
        jokes.add("Q: Why are fish so smart? A: Because they live in schools.");
        jokes.add(" Q: What fish only swims at night? A: A starfish.");
        jokes.add("Q: Why is a fish easy to weigh? A: Because it has its own scales.");
        jokes.add("Q: What animals are on legal documents? A: Seals.");
        jokes.add("Q: What do you get when you cross a snake and a pie? A: A pie-thon.");
        jokes.add("Q: What is 'out of bounds'? A: An exhausted kangaroo.");
        jokes.add("Q: What did the buffalo say to his son when he went away on a trip? A: Bison.");
        jokes.add("Q: Why didn't the boy believe the tiger? A: He thought it was a lion.");
        jokes.add("Q: What animal has more lives than a cat? A: Frogs, they croak every night.");
        jokes.add("Q: What did the spider do on the computer? A: Made a website.");
        jokes.add("Q: What did the computer do at lunchtime? A: Had a byte.");
        jokes.add("Q: What does a baby computer call his father? A: Data.");
        jokes.add("Q: Why did the computer keep sneezing? A: It had a virus.");
        jokes.add("Q: What is a computer virus? A: A terminal illness.");
        jokes.add("Q: Why was there a bug in the computer? A: Because it was looking for a byte to eat.");
        jokes.add("Q: Why did the computer squeak? A: Because someone stepped on its mouse.");
        jokes.add("Q: What do you get when you cross a computer and a life guard? A: A screensaver.");
        jokes.add("Q: Where do all the cool mice live? A: In their mousepads.");
        jokes.add("Q: What do you get when you cross a computer with an elephant? A: Lots of memory.");
        jokes.add("Q: What is black; white; green and bumpy? A: A pickle wearing a tuxedo.");
        jokes.add("Q: What do you call cheese that isn't yours? A: Nacho cheese.");
        jokes.add("Q: What's the best thing to put into a pie? A: Your teeth.");
        jokes.add("Q: Waiter, this food tastes kind of funny? A: Then why aren't you laughing?");
        jokes.add("Q: Did you hear the joke about the peanut butter? A: I'm not telling you. You might spread it.");
        jokes.add("Q: Why did the fisherman put peanut butter into the sea? A: To go with the jellyfish.");
        jokes.add("Q: Why shouldn't you tell an egg a joke? A: Because it might crack up.");
        jokes.add("Q: What did the baby corn say to it's mom? A: Where is pop corn?");
        jokes.add("Q: What kind of nuts always seems to have a cold? A: Cashews.");
        jokes.add("Q: Waiter, will my pizza be long? A: No sir, it will be round.");
        jokes.add("Q: Why did the banana go to the doctor? A: Because it wasn't peeling well.");
        jokes.add("Q: What is green and brown and crawls through the grass? A: A Girl Scout who has lost her cookie.");
        jokes.add("Q: What is white, has a horn, and gives milk? A: A dairy truck.");
        jokes.add("Q: What candy do you eat on the playground? A: Recess pieces.");
        jokes.add("Q: Why don't you starve in a desert? A: Because of all the 'sand which is' there.");
        jokes.add("Q: How do you make a walnut laugh? A: Crack it up.");
        jokes.add("Q: Why shouldn't you tell a secret on a farm? A: Because the potatoes have eyes and the corn has ears.");
        jokes.add("Q: What are twins favorite fruit? A: Pears.");
        jokes.add("Q: If a crocodile makes shoes, what does a banana make? A: Slippers");
        jokes.add("Q: What do you give to a sick lemon? A: Lemon aid");
        jokes.add("Q: How do you make a milk shake? A: Give it a good scare.");
        jokes.add("Q: What do you call a peanut in a spacesuit? A: An astronut");
        jokes.add("Q: What kind of keys do kids like to carry? A: Cookies");
        jokes.add("Q: Why don't they serve chocolate in prison? A: Because it makes you break out.");
        jokes.add("Q: What cheese is made backwards? A: Edam.");
        jokes.add("Q: How can you tell the ocean is friendly? A: It waves.");
        jokes.add("Q: What kind of hair do oceans have? A: Wavy");
        jokes.add("Q: What did Mars say to Saturn? A: Give me a ring sometime.");
        jokes.add("Q: What did the big flower say to the small flower? A: What's up Bud?");
        jokes.add("Q: Where does seaweed go to look for a job? A: The kelp wanted section.");
        jokes.add("Q: When is the moon the heaviest? A: When it's full");
        jokes.add("Q: What type of songs do the planets sing? A: Nep-tunes");
        jokes.add("Q: What kind of flower grows on your face? A: Tulips");
        jokes.add("Q: What washes up on very small beaches? A: Microwaves");
        jokes.add("Q: What do you call an attractive volcano? A: Lava-ble");
        jokes.add("Q: What did the big flower say to the little flower? A: Hey, bud.");
        jokes.add("Q: Why did the policeman go to the baseball game? A: He heard someone had stolen a base.");
        jokes.add("Q: Why did the book join the police? A: He wanted to go undercover.");
        jokes.add("Q: Why was there thunder and lightning in the lab? A: The scientists were brainstorming.");
        jokes.add("Q: What do lawyers wear to court? A: Lawsuits");
        jokes.add("Q: What did the lawyer name his daughter? A: Sue");
        jokes.add("Q: What kind of car does a farmer drive? A: A cornvertable");
        jokes.add("Q: What do you call a flying police officer? A: A helicopper");
        jokes.add("Q: How did the farmer mend his pants? A: With cabbage patches");
        jokes.add("Q: Why did the lazy man want a job in a bakery? A: So he could loaf around");
        jokes.add("Q: Why did the farmer ride his horse to town? A: It was too heavy to carry.");
        jokes.add("Q: What do you call a happy cowboy? A: A jolly rancher");
        jokes.add(" Q: What did the ground say to the earthquake? A: You crack me up.");
        jokes.add("Q: Why did the music teacher need a ladder? A: To reach the high notes");
        jokes.add("Q: What's the worst thing you're likely to find in the school cafeteria? A: The Food");
        jokes.add("Q: What kind of plates do they use on Venus? A: Flying saucers");
        jokes.add("Q: Why did nose not want to go to school? A: He was tired of getting picked on");
        jokes.add("Q: How do you get straight A's? A: By using a ruler");
        jokes.add("Q: What did the pen say to the pencil? A: So, what's your point?");
        jokes.add("Q: Why did the kid study in the airplane? A: Because he wanted a higher education");
        jokes.add("Q: How did the music teacher get locked in the classroom? A: His keys were inside the piano.");
        jokes.add("Q: What object is king of the classroom? A: The ruler");
        jokes.add("Q: When do astronauts eat? A: At launch time");
        jokes.add("Q: What did the pencil sharpener say to the pencil? A: Stop going in circles and get to the point");
        jokes.add("Q: How does the barber cut the moon's hair? A: E-clipse it.");
        jokes.add("Q: What happened when the wheel was invented? A: It caused a revolution.");
        jokes.add("Q: What do librarians take with them when they go fishing? A: Bookworms.");
        jokes.add("Q: What is the world's tallest building? A: The library because it has the most stories");
        jokes.add("Q: What vegetables to librarians like? A: Quiet peas");
        jokes.add("Q: Why did the clock in the cafeteria run slow? A: It always went back four seconds.");
        jokes.add("Q: Why didn't the sun go to college? A: Because it already had a million degrees");
        Random random=new Random();
        int jokesArrayListIndex=random.nextInt(jokes.size());
        return jokes.get(jokesArrayListIndex);
    }
}
